# name: Go Test

# on:
#   push:
#     branches:
#       - main  # Trigger on push to main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Go tests
#         run: go test ./... -v

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test
#     if: ${{ success()}}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Run Go tests
#         run: go test ./... -v

#       - name: Trigger Render Deploy Hook
#         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}


# CODE CHANGE 

# name: Go Test

# on:
#   push:
#     branches:
#       - main         # For deployment after merge
#   pull_request:       # For test checks before merge-

# jobs:
#   test:
#     name: Run Go Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.21'

#       - name: Run Go tests
#         run: go test ./... -v

#   deploy:
#     name: Deploy to Render
#     runs-on: ubuntu-latest
#     needs: test
#     if: github.ref == 'refs/heads/main' && success()
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Trigger Render Deploy Hook
#         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}


# NEW CODE 

name: Go Test & Deploy

on:
  pull_request:          # Run tests when PR is created or updated
  push:
    branches:
      - main             # Run deployment when PR is merged to main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run tests during PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Go tests
        run: go test ./... -v

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
