name: Go Test

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Go tests
        run: go test ./... -v

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    # if: ${{ success()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Go tests
        run: go test ./... -v

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
